Repository atom-community/atom-script, pull requests merged in 2020-12, with the labels that each got.

#2335 Fix the tests + Cross-platform GitHub Actions
  .gitattributes
  .github/workflows/CI.yml
  .github/workflows/bump_deps.yml
  .gitignore
  .travis.yml
  lib/header-view.js
  lib/runner.js
  lib/script-options-view.js
  lib/script-view.js
  package-lock.json
  package.json
  spec/code-context-spec.js
  spec/grammars-spec.js
Labels: tests

#2240 feat: support for ConTeXt MkIV and LMTX
  lib/grammars/doc.coffee
Labels: enhancement

#2338 Reflect Perl6 to Raku rename
  README.md
  lib/grammars/perl.coffee
  package.json
Labels: new grammar

#2203 chore: fix python3 example/color.py'
  examples/color.py
Labels: tests

#2340 feat: use atom-space-pen-views-plus
  lib/header-view.js
  lib/script-input-view.js
  lib/script-options-view.js
  lib/script-profile-run-view.js
  lib/script-view.js
  package.json
Labels: dependencies, ui

#2341 feat: switch to `@babel` packages
  lib/grammars/babel.config.js
  lib/grammars/coffeescript.coffee
  lib/grammars/javascript.js
  package.json
Labels: dependencies

#2336 feat: update dependencies
  package.json
Labels: dependencies
