Repository atom-community/atom-script, pull requests merged in 2021-03, with the labels that each got.

#2419 fix: if arg is not string assign it
  lib/runner.js
Labels: bug

#2420 fix: try catch ansi-to-html
  lib/script-view.js
  spec/fixtures/issue_2358.py
Labels: bug

#2422 fix: misc bug fix + update dependencies + eslint fix
  .eslintignore
  .eslintrc.json
  .eslintrc.yml
  lib/code-context-builder.js
  lib/code-context.js
  lib/command-context.js
  lib/grammar-utils.js
  lib/grammar-utils/R.js
  lib/grammar-utils/d.js
  lib/grammar-utils/java.js
  lib/grammar-utils/lisp.js
  lib/grammar-utils/matlab.js
  lib/grammar-utils/nim.js
  lib/grammar-utils/operating-system.js
  lib/grammar-utils/perl.js
  lib/grammar-utils/php.js
  lib/grammars.js
  lib/grammars/javascript.js
  lib/link-paths.js
  lib/runtime.js
  lib/script-input-view.js
  lib/script-options-view.js
  lib/script-options.js
  lib/script-profile-run-view.js
  lib/script-view.js
  lib/script.js
  lib/view-runtime-observer.js
  package.json
  pnpm-lock.yaml
  spec/code-context-builder-spec.js
  spec/code-context-spec.js
  spec/grammars-spec.js
  spec/runner-spec.js
  spec/script-options-spec.js
  spec/script-options-view-spec.js
Labels: bug, dependencies, general

#2409 Make position of output panel configurable
  lib/script-view.js
  lib/script.js
Labels: enhancement

#2423 feat: decaffeinate
  lib/grammar-utils.js
  lib/grammars.js
  lib/grammars/apple.coffee
  lib/grammars/apple.js
  lib/grammars/c.coffee
  lib/grammars/c.js
  lib/grammars/coffeescript.coffee
  lib/grammars/coffeescript.js
  lib/grammars/database.coffee
  lib/grammars/database.js
  lib/grammars/doc.coffee
  lib/grammars/doc.js
  lib/grammars/fortran.coffee
  lib/grammars/fortran.js
  lib/grammars/haskell.coffee
  lib/grammars/haskell.js
  lib/grammars/index.coffee
  lib/grammars/index.js
  lib/grammars/java.coffee
  lib/grammars/java.js
  lib/grammars/javascript.js
  lib/grammars/lisp.coffee
  lib/grammars/lisp.js
  lib/grammars/lua.coffee
  lib/grammars/lua.js
  lib/grammars/ml.coffee
  lib/grammars/ml.js
  lib/grammars/perl.coffee
  lib/grammars/perl.js
  lib/grammars/php.coffee
  lib/grammars/php.js
  lib/grammars/python.coffee
  lib/grammars/python.js
  lib/grammars/ruby.coffee
  lib/grammars/ruby.js
  lib/grammars/shell.coffee
  lib/grammars/shell.js
  lib/grammars/windows.coffee
  lib/grammars/windows.js
  lib/runner.js
  lib/script.js
  spec/grammars-spec.js
Labels: enhancement

#2426 chore: install types packages
  package.json
  pnpm-lock.yaml
Labels: dependencies

#2427 chore: use temp instead of tempy
  package.json
  pnpm-lock.yaml
  spec/code-context-spec.js
  spec/grammars-spec.js
Labels: dependencies

#2428 fix: use temp in grammars + fix various bugs
  examples/bubble.jl
  lib/command-context.js
  lib/grammar-utils.js
  lib/grammars/c.js
  lib/grammars/coffeescript.js
  lib/grammars/fortran.js
  lib/grammars/index.js
  lib/grammars/java.js
  lib/grammars/javascript.js
  package.json
  pnpm-lock.yaml
Labels: bug, dependencies, enhancement
